### ISSUE TITLE
wis2box-ctl.py start issue: Named volume is used in service  mosquitto/pygeoapi but no declaration was found in the volumes section.

### ISSUE THREAD

**Issue by davidpodeur** [wmo-im/wis2box#145]
I have followed the Quickstart procedure but I bump into this:

```
[rocky@vps-1b403fa7 wis2box]$  python3 wis2box-ctl.py start
ERROR: Named volume "${PWD}/data:/data/wis2box/data:rw" is used in service "mosquitto" but no declaration was found in the volumes section.
```

Funny enough, if I repeat the command, I sometimes get another (related) error:

```
[rocky@vps-1b403fa7 wis2box]$  python3 wis2box-ctl.py start
ERROR: Named volume "${PWD}/data:/data/wis2box/data:ro" is used in service "pygeoapi" but no declaration was found in the volumes section.
```

Context:

```
rocky@vps-1b403fa7 wis2box]$ cat tests/test.env
# Required
# Host machine data directory path
WIS2BOX_HOST_DATADIR=${PWD}/tests/data

# Optional
# Environment variable overrides
WIS2BOX_LOGGING_LOGLEVEL=DEBUG
WIS2BOX_DATA_RETENTION_DAYS=30
```

```
rocky@vps-1b403fa7 wis2box]$ cat /etc/centos-release
Rocky Linux release 8.5 (Green Obsidian)
```

```
[rocky@vps-1b403fa7 wis2box]$ /usr/bin/docker-compose  --version
docker-compose version 1.25.0, build 0a186604

```

**Comment by webb-ben** [comment]
Hi @davidpodeur. `dev.env` uses interpolation to get the absolute path of the working directory with `${PWD}` ([dotenvy](https://hexdocs.pm/dotenvy/dotenv-file-format.html#interpolation-a-k-a-variable-substitution) docs). It seems like your machine is passing the un-interpolated value for `WIS2BOX_HOST_DATADIR` to docker-compose. Because it is passing a string (i.e. `WIS2BOX_HOST_DATADIR=${PWD}/test/data`) instead of the path to data (i.e. `WIS2BOX_HOST_DATADIR=/home/runner/work/wis2box/wis2box/tests/data`) docker-compose is trying to mount the volume named `${PWD}/test/data` (which doesn't exist) instead of mounting the directory from the host machine into the container.

I know this is an issue for windows machines that use `cd` instead of their Linux/Unix counterpart, `PWD`... 

Some ideas:
- Add PWD to dev.env:
```
# Required
# Host machine data directory path
PWD=/my/working/directory
WIS2BOX_HOST_DATADIR=${PWD}/tests/data
```
- Try `${pwd}` or `${cd}`. This is second because I am not sure about the system environment variables on an OS basis. I don't want to send you on a wild goose chase for something that could be easily hardcoded.

Hope this helps! Let me know how it goes :)
