### ISSUE TITLE
add docs for publishing data via different protocols

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#150]
wis2box data publication is made available via API, WAF and MQTT notifications via same underlying volume / directory of data.

Add docs to explain this with the idea of publishing the data directory/volume via different protocols (samba, WebDAV, etc.) via additional containers.

cc @golfvert

**Comment by golfvert** [comment]
For data that is received from the outside, it would be interesting to have:
- the folder (accessible via WAF) also available as a CIFS share. It can be done by adding a samba docker container sharing the "WAF" volume 
- we could also consider, to facilitate the transition from the current PUSH method to the PULL one, adding an FTP/SFTP distribution mechanism in the box. All files in the WAF could be pushed to e.g. a legacy system allowing to keep the traditional flow of data.

**Comment by petersilva** [comment]
* um... ideally, the thing that watches files is installed as close as possible to reception.. right now, the data- 
  consumer package has to poll the ingest directory, because it is "remote" (separate container from file server 
  receiving the files.) Ideally, the watch would be within the container that has whatever thing is doing file 
  reception (be it samba, or ftp, or sftp, or )

* the Sr3 stack has senders that (supporting SFTP and FTP) than are fed in real-time from MQP... that's how 
  we use it internally for sending terabytes around daily.  Legacy clients don't know they are actually using 
  pub/sub ;-) It's just add containers and configs, almost a carbon-copy of existing publishers.

**Comment by tomkralidis** [comment]
FYI PR in #151
