### ISSUE TITLE
Collection not found

### ISSUE THREAD

**Issue by kennethkoker** [wmo-im/wis2box#182]
Hi everyone, 

I am trying to implement the wis2box but running the command "wis2box metadata station publish-collection" from the quick guide gives the RuntimeError: {"code": "NotFound", "description": "Collection not found"}.

I am using Docker on Windows.

**Comment by webb-ben** [comment]
Hello @kennethkoker! Welcome to the issues. 

When we call `wis2box metadata station publish-collection`, items published to the discovery metadata will be crawled for link relations to collections with data from that station. The error is because we have published discovery metadata about a topic but have not yet published that collection to the API. The stations are still published to the API and you should be able to continue on following the quickstart; Perhaps a more appropriate message would be a `Warning` about the error encountered instead of an Error.

Running `wis2box metadata station publish-collection` at the end of the quickstart should yield a different result. Let me know how it goes. In the meantime, will try to clarify this. I hope this helps!

**Comment by kennethkoker** [comment]
Thanks @webb-ben for the clarification. I was able to run through the quick guide even with the Error/Warning.
