### ISSUE TITLE
add security scanners for containers

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#652]
Add trivy via GitHub Actions in order to scan containers for vulnerabilities.

**Comment by maaikelimper** [comment]
I ran trivy on the wis2box-api, it found one issue with severity=HIGH
https://github.com/wmo-im/wis2box-api/actions/runs/9615735356/job/26523621849

**Comment by maaikelimper** [comment]
question: should the GHA only fail on severity=CRITICAL ?

**Comment by tomkralidis** [comment]
1. can we update `wmo-im/dim_eccodes_baseimage` to 22.04 ?
2. we should be checking for `severity: CRITICAL,HIGH`

**Comment by maaikelimper** [comment]
@tomkralidis how to proceed ?
- Do I make new issues for each failed service in the wis2box-repo or in the original repo ?
- Should I scan -all- containers (so also nginx, minio, prometheus etc.) or just those containers build out of wmo-im repositories ?

**Comment by tomkralidis** [comment]
- add issues in this issue tracker regardless of the original repo, since we are running the GitHub Action here
- only scan non-upstream

**Comment by maaikelimper** [comment]
after updating dim_eccodes_baseimage to use Ubuntu 22.04, wis2box-api now passes the vulnerability scan:
![image](https://github.com/wmo-im/wis2box/assets/19169339/7957828d-56b6-4a3a-996a-75e809b74e78)

**Comment by tomkralidis** [comment]
2024-07-24:

- we need to address current state of #699

**Comment by tomkralidis** [comment]
2024-08-14:

- @tomkralidis to assess #699 and which images need to be addressed/fixed

**Comment by maaikelimper** [comment]
This task is quite difficult due to the many images and upstream dependencies.

Certain packages have no active developers like wis2box-ui, for which the node-version in the base-image needs to be updated, which I'm hesitant to due as there is a high risk of additional work required when doing so due to downstream dependencies.

New vulnerabilities can be discovered over time, so we would require contineous updates to make this security scanner pass.

Each vulnerability found needs to be carefully studied as many do not appear to be relevant as actual security concerns as they depend on specific features that we may not use.

https://avd.aquasec.com/nvd/2024/cve-2024-24790/

The scan itself regularly fails with the error:
`Fatal error	init error: DB error: failed to download vulnerability DB: database download error: oci download error: `

A manual re-run often works around this, but it has to be noted that adding this GitHub-action will introduce significant additional work for developers for each new PR to pass this test.

**Comment by maaikelimper** [comment]
In order to make this task more manageable I will add the trivvy-scans (and resolve vulnerabilities) to images build outside of this repo, namely:
wis2box-api
wis2box-ui
wisb2ox-webapp

Then I can reduce the number of trivvy-scans required to be added in this repo

**Comment by maaikelimper** [comment]
FYI, I found a workaround for the TOOMANYREQUESTS issue by setting a different TRIVY_DB_REPOSITORY in the env

**Comment by tomkralidis** [comment]
FYI we will need a trivy GHA setup for https://github.com/wmo-im/wis2box-auth as well.

**Comment by tomkralidis** [comment]
> FYI we will need a trivy GHA setup for https://github.com/wmo-im/wis2box-auth as well.

Done in https://github.com/wmo-im/wis2box-auth/commit/6e727c2834d3894a512d724bd03f0a165bb0cce2
