### ISSUE TITLE
Request for Addition of Data Formats for Message Publication via wis2box webapp (updated SYNOP form?)

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#709]
We have received the following request from Francilly Samba from Congo:

_As an operator of a WIS2 node (wis2box), I would like to publish CLIMATs, TEMP, PILOT, and SHIP messages through the wis2box-webapp interface.
To this end, could you please add the following templates or data formats: FM 71, FM 35, FM 32, and FM 13?_

**Comment by maaikelimper** [comment]
@efucile and @david-i-berry can you please comment on  this issue ?

**Comment by efucile** [comment]
TEMP and PILOT must be produced in BUFR format using the software provided with the observing system because the old alphanumeric format does not have all the information required for the conversion to BUFR.
CLIMAT is a climate specific format that is going to be replaced by DAYCLI for which there is already an example in the wis2box training material.
SHIP could be implemented, but we need to have a clear use case for a web app like SYNOP. In general SHIP should reach the wis2box in BUFR format.

**Comment by maaikelimper** [comment]
closing as not planned for now
