### ISSUE TITLE
Issue with Adding Station Metadata in Bulk in Version 1.0b7

### ISSUE THREAD

**Issue by DianaPaik** [wmo-im/wis2box#711]
I am currently setting up a web application using version 1.0b7 of wis2box. 
However, I encountered an issue while trying to map a collection to a specific discovery using the following commands:

### wis2box data add-collection /data/wis2box/metadata/discovery/buoy-test1.yml

The problem arises when adding station metadata in bulk. 
It appears that the stations do not get added to multiple datasets but are instead applied to only **one dataset.**
_**In version 1.0b6**_, using the same method, station information was displayed for all datasets.

I attempted to resolve this issue using queries within the web application rather than through the API, but the problem persists.

Could you please provide guidance or a solution for this issue?

**Comment by maaikelimper** [comment]
Hi @DianaPaik  thank you for contacting us.

Please note this is not an issue relating to adding station metadata in bulk in version 1.0b7. 

Rather in version 1,0b7 the option to display a observations for stations on map in the wis2box-ui is only available for datasets with a topic ending with 'surface-based-observations/synop'

This is because the wis2box-ui currently does not provide a way to accurately display the location of moving platforms (/ship, /buoy) nor it can it correctly display the full information from a temp-profile.

Note that If you have configured the bufr2geojson-plugin on your dataset the output of bufr2geojson can be accessed via the collection in the oapi-endpoint.
